# Generated by Django 4.2.1 on 2023-05-27 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_notify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notify',
            name='status',
        ),
    ]
