# Generated by Django 4.2.1 on 2023-06-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_assignsubscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='trainer/'),
        ),
    ]
