# Generated by Django 4.2.1 on 2023-06-02 16:37

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_trainer_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='img',
            field=imagekit.models.fields.ProcessedImageField(upload_to='trainer/'),
        ),
    ]
