# Generated by Django 4.2.1 on 2023-06-19 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
