"""
Django settings for gymManageSys project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^0$i9@5e=))ra53+kxxj994y!%k6a0#2%j1q9#qy!gpi8qc8_-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'imagekit',
    'main',
   # 'user',
    #'tailwind',
    #'theme',
]

TAILWIND_APP_NAME='theme'
INTERNAL_IPS=["127.0.01"]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gymManageSys.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gymManageSys.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Define the paths for indexed and original documents
INDEXED_DOCUMENTS_PATH = os.path.join(BASE_DIR, 'indexed')
ORIGINAL_DOCUMENTS_PATH = os.path.join(BASE_DIR, 'original')


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'postgres',
        'USER':'postgres',
        'PASSWORD':'1234',
        'HOST':'127.0.0.1',
        'POST':'5050'
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL="/media/"
MEDIA_ROOT=os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS={
    "site_title": "GMS Admin",
    "site_header": "GMS Admin",
    "site_brand":"ስፖርት ለጤናዎ!!!",
    #"site_logo":"F:\\Django\\GYM\\gymManageSys\\main\\static\\image\\enquery.jpg",
    "order_with_respect_to": ["auth","main.banners","main.service", "main.enquiry","main.gallery",
        "main.galleryImage","main.Page","main.Faq","main.SubPlan","main.SubPlanFeature"],
}

APPEND_SLASH = False

LOGIN_REDIRECT_URL='home'
LOGOUT_REDIRECT_URL='login'

EMAIL_BACKEND='django.core.mail.backend.console.EmailBackend'
# CHANEL_LAYERS={
#     "default":{
#         "BACKEND":"Chanels_redis.core.RedisChanelLayer",
#         "CONFIG":{
#             "hosts":[("127.0.0.1",6379)]
#         }
#     }
# }